apiVersion: redhatcop.redhat.io/v1alpha1
kind: EgressIPAM
metadata:
  name: example-egressipam
spec:
  # Add fields here
  cidrAssignment:
    - labelValue: us-east-1
      CIDR: 192.169.0.0/24
    - labelValue: us-east-2
      CIDR: 192.170.0.0/24
  nodeLabel: topology.kubernetes.io/zone
  nodeSelector:
    node-role.kubernetes.io/worker: ""
    

