apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: egressipams.redhatcop.redhat.io
spec:
  group: redhatcop.redhat.io
  names:
    kind: EgressIPAM
    listKind: EgressIPAMList
    plural: egressipams
    singular: egressipam
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: EgressIPAM is the Schema for the egressipams API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: EgressIPAMSpec defines the desired state of EgressIPAM
          properties:
            cidrAssignment:
              items:
                properties:
                  CIDR:
                    type: string
                  labelValue:
                    type: string
                required:
                - CIDR
                - labelValue
                type: object
              type: array
            nodeLabel:
              type: string
          required:
          - nodeLabel
          type: object
        status:
          description: EgressIPAMStatus defines the observed state of EgressIPAM
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
